apiVersion: v1
kind: Secret
metadata:
    name: backup-bucket-credentials
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:tM/m5hnOAJCTbM+3hMyfmMftqsZTsGentw==,iv:8641CiYCK3lMdY2MmXevyUuX+mmWSK6yxLTM22kpe+E=,tag:Lxt2+kf33t4d20DhYwCzVg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Pd35FPeG/FcvfcUvkrXTgPeCDsE7Pmpt4jzEBIu6yA==,iv:jF9KWPNgv+xCNDrhNNxduSd+tejMIjVdagzOjBjuUpE=,tag:awWrn0Fj5oVPhBLKKWVLOA==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTE1XazJKMVJJeFVvOW9w
            cnprL0k5N2FGazBLc1lYelJGMzVxckMybUdzCk5kQmVLcXBCTlZCQXMwOGR5MVN0
            RVlkTzJ6Tm1tdGlmdGllQWk1QjI2Nm8KLS0tIGNBVEh3L0p1dEF2UkswM3RJQlh6
            K0NkaXZqSmVWUmJtQ2pHOTh4VStna3MKaP+Fudk/F9hIEbweq6ngEZ1ODcsdulyR
            umU1aR0R6tRgGSgrFtwVIWE76IKY55208XiEAGbXAq6fWr6M43Xpig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdzIzTERYZkZpQzJkOHcx
            YWljOGRjcEJ6UlJLSWFQbjhXSmU1b1VGS0RFCk1ESzVGRjl4elVhU2IwcC9scmQ1
            U1RyOUJncmNpbHBFaEZOOE5uMXdKU0UKLS0tIHJEOTZLMmhBZVMvS3VrZzcydCtX
            N3JxVnJMS2tRVWcvL1lIbU5yYWQ4eEEKWwELCdxnmjhjdiNmRQN5M4Bj62jVA/FO
            qhMQHuG1k6PQ5gCZlO5uAtTBvyDHxI0ELB97Mihpm9OKmAcF+SA4Ug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc2k3UWFNRG5LWDVNNmxG
            ZldvTnl1UTBuTWlWK2NPbS9ORW8rOUVnV2lVCjlsRTMrRk81MlZ0Qk1WSUZ1a1FX
            S0owSHI5UTZFSS9iNnM0RG5TZXVMR00KLS0tIEFQQVdKZGpjbXkzc3YyMXo4RWdj
            ZHhrVEF3WWgzbUhycXdraSs2ZzNGYUUKLu0BcfVBI4+k+7cL4XRY4anJ7rFUh3Iz
            wwlG2P+X4UxUHKzR377OKdlHJ47xzyaVrTqrP5ZNWqMVZXygaDKd7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T23:11:23Z"
    mac: ENC[AES256_GCM,data:Fw2A7SE/B+PniplR0NiDFL19eqqbFhL6gOqoSHjNT3ml0AFhUOfW9EITQAenAuiThq/DlUpREDM+VTxkHpf2U7f5073tMPW7iklNRMEhhAzoUGU1/DL+azm9JyqTyoQEY1Wi7VqzXAkmGdzAq0KhyJYNWk2oZw2v2njDpuqOQps=,iv:fOGGlDhQ+sm+lBEuaJyPYF/miQSzbSZ7b5VZxo64b1g=,tag:kPVC+t8+WA/NLJwgUUHd0A==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
