apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0lUudRpSTTx8,iv:AmzbFrPT57wp5H7faUAnTaJ119po+b3XnV28H5huf/4=,tag:bkn4/wBBQFRFcK6NzCm7Fg==,type:str]
    password: ENC[AES256_GCM,data:suUvuBuZqeNly4H7OTc5JQsDwwX6vhjCDCvVK/ACKrU=,iv:/QS5U6y0vD9H+eugdNchYI3kmB4NcOT5CYISPIPjJiI=,tag:9+0eyZbG8nMh8NV4VbQq5w==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUTFLQ1h0QStTb05IWXJ6
            T2NDdGxoOFozUDBHVlFvQnljU2tORkNWWFI0Cldoa21zWmUwVE51TWZmdHVRRjlP
            ZDMrWkNydUlFbTMyRXhVWGNMczArbGMKLS0tIDUvSUlqQ1dtR3FJUy9uWldLbzM4
            N3BjZzREbW1MTERSRnRWRk1NS3l0M2sKvmAGhfYcuJTlehoBEMBNr1olXfzJAbNi
            zKQ1/DtkjJw4tLhLJmMVnrdb4CMb4NK3G50J+C3QjTzIVQxo76inHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc2dDdFJtdHFycHorVkFr
            elRiM0xVWXByMGJtQ2pxYWtIUmREeFdiZkFnClMwOFRPTjRVYmp3TWVvTEdRdnVa
            LzdnZVVRdStZa21IT1BrWFE5eWtGRWsKLS0tIDBKNGw5SDNJTlJNRXg0Mk8rUm1P
            NGNuNEZHNVRpaVNWcWQ0d0prUWZKdUkK0kSMyN5i4EtOAPYtgn2kfe5a6YsGrsX2
            iz7ZGGfLraRaefofOUBFbd4yaxjem6mMDMjmTxFcfHuutEt90puG2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUmN1OG5OUEpPRTB3bTB2
            cm5hYzdqemVLVFlmOTBEM3VHY0hPMHVGeG1FCjNNM2pCYWNLTFp1Mm9JNGxyaTFC
            dEVCQ1l0YUJUSnU1ZEpvLzdKUHpTbXcKLS0tIDVxWlRQcDZrQ2M5VVhrTzBEa1JB
            TnB2WTFkNmtPSGZ1VWY4ZmIxK2FyMGcKHhBdQChVv8cUxAAVb46sdfQ5pVaot1Fk
            /ff7PyP/YRRf47DHs2BKHQ+mfGfNanSCfcyeimSoZndLgw/eQCHQHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T20:01:18Z"
    mac: ENC[AES256_GCM,data:CWfB7UK2UahJxZ7cp9Aa4kPVWp5VMMXu8LxphfxB9L0wplzE7DaRaoAkdDh5W9xCrRbzduJMoKpqjWSizlk1qoEPIAW59awEJAzWUzRcgHIRySig2msTgZ15gAummTxwISVRlnoXyMU1NamgqHe2rsX3YsA+RmXjdCnN20Mh0EQ=,iv:uQW7iOPbwqcS/KwWWUiQFq6puXK4twmsfMYAs7FYZHM=,tag:Zr5wv5r9CLYUwJZo1Zrbng==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:J91SvaeUIfWX,iv:pGUrawqOOLauaKDjt09eQAnEbNwsn5U1ma4PDXAGbNw=,tag:Cp4KGm2bc0THGpiL2UmUAA==,type:str]
    password: ENC[AES256_GCM,data:s5DQV+K34c3KNXEdsgYxypDyjrTjUnDLyLacHmQWvkc=,iv:oZxWt1QddZf13xlJ7qHZ6autTl5y0iR/i5ifi5Y/hwo=,tag:putAPaK/VOFY75Jx7xEaBg==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUTFLQ1h0QStTb05IWXJ6
            T2NDdGxoOFozUDBHVlFvQnljU2tORkNWWFI0Cldoa21zWmUwVE51TWZmdHVRRjlP
            ZDMrWkNydUlFbTMyRXhVWGNMczArbGMKLS0tIDUvSUlqQ1dtR3FJUy9uWldLbzM4
            N3BjZzREbW1MTERSRnRWRk1NS3l0M2sKvmAGhfYcuJTlehoBEMBNr1olXfzJAbNi
            zKQ1/DtkjJw4tLhLJmMVnrdb4CMb4NK3G50J+C3QjTzIVQxo76inHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc2dDdFJtdHFycHorVkFr
            elRiM0xVWXByMGJtQ2pxYWtIUmREeFdiZkFnClMwOFRPTjRVYmp3TWVvTEdRdnVa
            LzdnZVVRdStZa21IT1BrWFE5eWtGRWsKLS0tIDBKNGw5SDNJTlJNRXg0Mk8rUm1P
            NGNuNEZHNVRpaVNWcWQ0d0prUWZKdUkK0kSMyN5i4EtOAPYtgn2kfe5a6YsGrsX2
            iz7ZGGfLraRaefofOUBFbd4yaxjem6mMDMjmTxFcfHuutEt90puG2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUmN1OG5OUEpPRTB3bTB2
            cm5hYzdqemVLVFlmOTBEM3VHY0hPMHVGeG1FCjNNM2pCYWNLTFp1Mm9JNGxyaTFC
            dEVCQ1l0YUJUSnU1ZEpvLzdKUHpTbXcKLS0tIDVxWlRQcDZrQ2M5VVhrTzBEa1JB
            TnB2WTFkNmtPSGZ1VWY4ZmIxK2FyMGcKHhBdQChVv8cUxAAVb46sdfQ5pVaot1Fk
            /ff7PyP/YRRf47DHs2BKHQ+mfGfNanSCfcyeimSoZndLgw/eQCHQHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T20:01:18Z"
    mac: ENC[AES256_GCM,data:CWfB7UK2UahJxZ7cp9Aa4kPVWp5VMMXu8LxphfxB9L0wplzE7DaRaoAkdDh5W9xCrRbzduJMoKpqjWSizlk1qoEPIAW59awEJAzWUzRcgHIRySig2msTgZ15gAummTxwISVRlnoXyMU1NamgqHe2rsX3YsA+RmXjdCnN20Mh0EQ=,iv:uQW7iOPbwqcS/KwWWUiQFq6puXK4twmsfMYAs7FYZHM=,tag:Zr5wv5r9CLYUwJZo1Zrbng==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-db-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:huir7EqQ,iv:rQFW4rNvXLA+WRt3rmd9xuwKXxI9Z8H2ATMB7HTaNwU=,tag:mrrZBmQS6X4VN3iD04pjBQ==,type:str]
    password: ENC[AES256_GCM,data:VCt2TepLv0OR8055PS1yVszExBJ0kF1NxDH/XFc2eR4=,iv:l5AwGvEbo+1/G0+52q38q3bUj4rb6C8J6YfW59fN5VY=,tag:HDSZawpSgm/9m5d/sdmCzw==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUTFLQ1h0QStTb05IWXJ6
            T2NDdGxoOFozUDBHVlFvQnljU2tORkNWWFI0Cldoa21zWmUwVE51TWZmdHVRRjlP
            ZDMrWkNydUlFbTMyRXhVWGNMczArbGMKLS0tIDUvSUlqQ1dtR3FJUy9uWldLbzM4
            N3BjZzREbW1MTERSRnRWRk1NS3l0M2sKvmAGhfYcuJTlehoBEMBNr1olXfzJAbNi
            zKQ1/DtkjJw4tLhLJmMVnrdb4CMb4NK3G50J+C3QjTzIVQxo76inHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc2dDdFJtdHFycHorVkFr
            elRiM0xVWXByMGJtQ2pxYWtIUmREeFdiZkFnClMwOFRPTjRVYmp3TWVvTEdRdnVa
            LzdnZVVRdStZa21IT1BrWFE5eWtGRWsKLS0tIDBKNGw5SDNJTlJNRXg0Mk8rUm1P
            NGNuNEZHNVRpaVNWcWQ0d0prUWZKdUkK0kSMyN5i4EtOAPYtgn2kfe5a6YsGrsX2
            iz7ZGGfLraRaefofOUBFbd4yaxjem6mMDMjmTxFcfHuutEt90puG2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUmN1OG5OUEpPRTB3bTB2
            cm5hYzdqemVLVFlmOTBEM3VHY0hPMHVGeG1FCjNNM2pCYWNLTFp1Mm9JNGxyaTFC
            dEVCQ1l0YUJUSnU1ZEpvLzdKUHpTbXcKLS0tIDVxWlRQcDZrQ2M5VVhrTzBEa1JB
            TnB2WTFkNmtPSGZ1VWY4ZmIxK2FyMGcKHhBdQChVv8cUxAAVb46sdfQ5pVaot1Fk
            /ff7PyP/YRRf47DHs2BKHQ+mfGfNanSCfcyeimSoZndLgw/eQCHQHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T20:01:18Z"
    mac: ENC[AES256_GCM,data:CWfB7UK2UahJxZ7cp9Aa4kPVWp5VMMXu8LxphfxB9L0wplzE7DaRaoAkdDh5W9xCrRbzduJMoKpqjWSizlk1qoEPIAW59awEJAzWUzRcgHIRySig2msTgZ15gAummTxwISVRlnoXyMU1NamgqHe2rsX3YsA+RmXjdCnN20Mh0EQ=,iv:uQW7iOPbwqcS/KwWWUiQFq6puXK4twmsfMYAs7FYZHM=,tag:Zr5wv5r9CLYUwJZo1Zrbng==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
