apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pi-storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 100.64.0.3
    path: /srv/my_book/media_data
    readOnly: true
  mountOptions:
    - ro
    - nfsvers=4
    - hard
    - intr
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-pi-storage
  storageClassName: ""
