apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raspi5-cert-manager
  namespace: argocd
spec:
  project: system
  source:
    path: manifests/apps/raspi5/_system/cert-manager
    repoURL: https://github.com/TheBigLee/talos.git
    targetRevision: HEAD
  destination:
    namespace: cert-manager
    name: raspi5
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
