apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raspi5-local-kube-system
  namespace: argocd
spec:
  project: system
  source:
    path: 'manifests/apps/raspi5/_system/kube-system'
    repoURL: https://github.com/TheBigLee/talos.git
    targetRevision: HEAD
  destination:
    name: raspi5
    namespace: kube-system
  syncPolicy:
    automated: {}
