apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.27.0
      helm:
        values: |
          replicaCount: 2
    - chart: plugin-barman-cloud
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.3.1
  destination:
    namespace: cloudnative-pg
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
