apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuppr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
    - path: "."
      repoURL: oci://ghcr.io/home-operations/charts/tuppr
      targetRevision: 0.0.50
    - path: manifests/apps/talos/tuppr
      repoURL: https://github.com/TheBigLee/talos.git
      targetRevision: HEAD
  destination:
    namespace: system-upgrade
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
