apiVersion: v1
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:56iI1ebLVCZARydfmv6Fh3bVPpIc+8ZWnQZmnKQ5n0sw57IWVAJHxDDUzEo5qn2QNbRMycYaIqvfGy9NReSRtg==,iv:24X8QnsuBBZSa5cHuDd4StJ/Av1AImrFWJ2SFdmoW5s=,tag:one/Nx7fLUSqWGYLNRoFIw==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bk9lOGJLd1IrVWZEQkp1
            bWk3N2ZoVU5YMFpGOSszVnhzZUJXdHZvM0RvCnlLb3B2Um45d09QOS9VQVExU0p6
            SjVXekQ4VmlML2Q1QmhGM2ZGZUZuTU0KLS0tIE1rQndHMTRJWThvUVZrbTZzcEJ0
            cXBaaHBFVXRrcEJXdHk3c1p0cTNYL0EKMwHJ7TD9h7TCChCojzxj1Jvm3e3OHNbT
            8kdTeOkCrKhBtiBrT2PeXQ31gslxg6i0U1BRw9biCvegRLnYILOJgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTmpFRjdKeEFPdi9hbVA1
            YTUvc0FtTUhuOW5DTkZCUlNzRm1pcENNSzAwCjNKR3QyczlYcStOV1ZxWkRsYVRO
            SHhsVWFjT1RMWitqdW5jOGVSUElUSEEKLS0tIEU3ZUJtOXZUL01KdUxsbHBGbjQw
            aHlPUDV4MVlmS3BXY3dzc0NsYmxTUGsKQlb/YBgZnMvsns4KLAtkulB/Ei7Uakw+
            6C1cCKJuE/F5Z5wdp+kCzMMjUlXSoGBgrSkiNYTxOBbtDNuN5OuyXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRExmT3dIbldoQWdJTHdX
            WE1QMXlVK2RDbVBkVVFWQXhHY2ZRZ1hGMFNRClRCaXV1enlRZ2lMWmJVL3RBT1dy
            REZ5WStuVlFHTUd1bVUvWE56ck1mWjQKLS0tIEZaWHdyaitmSXVhMmxrMzdLYVYv
            eDNZaFFkdndSSHRsYU9VNEZWekdIcFUKXLxoZwjW7S1QfoTzF4L4F6ItoPKN2N3d
            U3aBTUpgTDkGJdmlDZWHudfvlXcgkt63qke5qpAtUcLAul7hVIO1Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T13:35:50Z"
    mac: ENC[AES256_GCM,data:1LAIyi4OL/WUkgcyEl+mwzmmUz97STUMIm2jkG4KeQys/9dnuwtlPb9nEGWgLXXeYhJOADd2nfRRYtKg+vOe895rp4MtE/dP3s/zx0ePi/25gTaTXgSXQahCwtR6ZosGZaBx4Jc42AEcrs6jHnio/YPlftA8y3potM/76j0CgF0=,iv:h1dIMo2TG6sK6wPj/g2UXiqp8oBxOYY7T7NRWWvMFU8=,tag:g/AQnw73HbBch6DXFvTL7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
