apiVersion: v1
kind: Secret
metadata:
    name: global-s3-credentials
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:rggxdffujqMHVkQ4mF8fe2bquRUiVFCAhA==,iv:Ml2SlrOhAgZYc971VDV4pc4xMqilsFmFuMRs/3Iq/U4=,tag:iWKIV5FE/P52sVBT7YZoYg==,type:str]
    access-key-secret: ENC[AES256_GCM,data:cGvZ/YHqQce6P8Wvtp/Zpac7tFWzB07yWb5+yVsf6Q==,iv:8by/aKOpY2c3KTt/OmqGLOaZQqKj7VWRdBJalVgUFZ4=,tag:5ogiCo4vV4ZrKQYc+btjNg==,type:str]
    endpoint: ENC[AES256_GCM,data:VNKqkTRTM9arxO48G3OJKWhC+ScosUaKXxyxR2sPAJgb,iv:0dpxAO09JOk70oQoFZWvOZN6lVfPvRjjsKrRClWOdHY=,tag:lvDHCUsr+X2egXgU/l2Rjg==,type:str]
    bucket: ENC[AES256_GCM,data:EFAkv9WjzBAjnEYmDJxpFHUGqcHe,iv:QzJEooFdZEP1z4I1cMyAN3esx3o49vK7DAtOJYim2oY=,tag:QQZlwPHOMzUAc2eDttky+A==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL2JUSUpMdzduaGdONXJM
            Um1TRzQvRWs4Q3dKWTA2cmZXSWtjYUdzRDNRCkFkMnZvaDN4TCtHS3JlbElBcm9C
            N3h0RGl4VVFMT1ZMNnlObXRJNTlEbzQKLS0tIE1KY21KLzlJdlFObWFGa0kyWStZ
            MUh4MG1ZMmFCcndMSlVKMmVtY084UUEKKdZyOHYRHnS+ZzFFJmiKljN2x0FJOh2s
            XNXs59SeYoXN6fTzQSlcGITxYU61hddNEOJtCzmKdaFhXGtDrBjh4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVUdoUy80aTkvQjdEbUZs
            d29yaU5wcjdrM3kzaEQzQ1BjRDJKRXdwL1R3CjVFYy85b0VIdjlLY01aUDdKVnpi
            NjBkQVZ3L2lQTXpneWUwdFh0dlN0MEEKLS0tIHlQc3NwUFhFMEU5WUxHOFY3SlhS
            ZmR4L3d3M1JweTlqbzNxekZWSWM2cUEKAvMCWymndQPv1mOXZx5rTkkiBRzOk6tS
            heZph3Gisdq/5PnvAgQCSkD/If3qd/zkAlk0Eb3XCN2SrSMBIfwSEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFalpOSCtDWCtJeVRrRGpB
            TzVxazMzYlJTRXdtekZNZTFQYS9mdlAyeldFClZmaWRsMlVReVhDcFdLbVRyd1ly
            K2xVZTNhZWlwa1plMGgxRnF2RnJKRUUKLS0tIHJGWmhkaVZnR2FOUmN6YkhTNzV4
            V1hKK2RVU2xIWjQxVE5iUVVzL0hEcm8K7UxXO7N+SAI74waCCSS3cxg5cCwoep9E
            /aL7sDcfZFufcqdYOSLeo42JSlAIALB0w2pBsKkts9PcrcmgJ80cnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T17:07:55Z"
    mac: ENC[AES256_GCM,data:DmitACh1e8wkO12qWQblVpLzTDxRcZiW0XYwXwY/6oGjkQVwN4tW592rxTZ8wtsn4cbwPh8H6u24l1UYLHeJttmHErYQUVizEgy3xQY53W9mv34ZmiStzgYvdf6txwTl68MfPYrZgXJu20pCIdATm1mySJN3jNgusfDLRT5bsXw=,iv:1TIaRfteykxK3G6+nYAEHA7/h7NM7oVfFq0euroBcUA=,tag:IlLIkT2CZk8w2LCkHOrJuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
