apiVersion: v1
kind: Secret
metadata:
    name: global-backup-secret
type: Opaque
stringData:
    secret: ENC[AES256_GCM,data:tnKXVJsfBbPietOEnABTh7AmRiqS7A8FCvJrGKDVqZE=,iv:QJyACCklCfzHsjW2NCCcWk6TOdm5yROnOXPhWD5Nkdc=,tag:/QfAtWcaoXbQ2Y2O89//HA==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UjJZQlZWaE82QWpXdDB5
            UW1Fazk4alpkWnE4Y2FGbWFlbERMaHZnRzBnCm5MclBUdWgrcGNWWUtHempOaFE0
            WkQzWm1Dd05nOFZ0OWlHRlhYZzhUUFEKLS0tIDErcXdsZkVTYmYzUGRGNWh3S3ZG
            aTZoUHA3WE1QT1NoOGFoZ2pUdXpSWDQKVozfF65IRtl4PYSo2BNXCvKiEeXksZXD
            xSR0mafJcuK+ylyzC5T9teEDcc+7m1fyHQR5vmmZxew6NuXrnsD1tw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcXlaVENuOEtBZWg1U3dD
            dThYWlNRaUJEcWM5ZDE4SDFJeHJNWWh0dm5nCmliVEs3Vk9sMUNveTh3MlY1RTQv
            OHhpQ0hEbGcvSG9SUTVYV3Z5Uzk5eWcKLS0tIDhFdXhaMGlVS1RsYjRhd0tpZ0Jj
            cVNuUzVyM1Z6bGVKVWhPODZtcEp6bkkKJiddX5+7XjemX7cZ5SKYIeEHOfz+TiAN
            00qnVEVZM81Q6E37La4R109X9gkOFS8vSVTbfTIAX49TIGWwYj3POQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUWJNWVpzeVgyc1BBQjZs
            MTJaT1htMGdGYWIwTWdRZzRhYUV0WHc1ZkE4CmR1ZkdxUitvdUlKWWQ5QzNKUXM3
            eEkrSktCSHc0a09MaktPYytFYURwQzQKLS0tIDluOXJxTWdVUXZoSkZuQXQ2V2lG
            eFcxbDBiNXl5WFF0VlJ4QytOYTNNZlEKM+qZdutnwIV8S/SQnbHjgHvyOxtiTPSH
            MwZSRppSTzR598u4bveRMzP8xs1HcJot3YWHMIiSc38IC1z8vLO7Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T17:08:36Z"
    mac: ENC[AES256_GCM,data:cK16X8np+PRAWdYl4zDiFXTySp6u8uA4PbeacVTOYbFE3Cw8FIhlmTMOAVoIEZL/e3xb5h9phRjIiEgHPsfxVTZZRjXTVQwlG1R7RX6TDzGnZecPDJyoUP4KbBcYE5yH19JsLTUX/jdG/4jgemYSrRIQ+A8f3HyTko/5ttKmXUU=,iv:VWbYVUjTyNbj9BRdtulmU3roRj+WCrUnu/6azY+Qhrw=,tag:4HedeEeUPCIv4/pXOLLT4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
