---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: influxdb-route
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik-system
    sectionName: websecure
  hostnames:
  - "influxdb.bigli.io"
  rules:
  - backendRefs:
    - name: influxdb
      port: 8086
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: influxdb-route-redirect
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik-system
    sectionName: web
  hostnames:
  - "influxdb.bigli.io"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
