apiVersion: v1
kind: Secret
metadata:
    name: influx-credentials
type: Opaque
stringData:
    influxdb-password: ENC[AES256_GCM,data:tOF20i4LGa9Jl4YR8OoDtvpRYMKb4O7ul8efc2YrEm4=,iv:nLKNaFJMRtS60oQam8IFcxmt6VPkGUv3a+pjjQm+tRc=,tag:tA2SkxFrqp1rf/W792Q49g==,type:str]
    influxdb-user: ENC[AES256_GCM,data:iuc5ILd/Ub0=,iv:pUegbyYYUuFAEPgTHetwQiWFR1VuuqMKx5EirXEo3qo=,tag:gkdozI378DEtEhO6xVzfQw==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJT21CR2Zsb2M2LzhSREVD
            QmhWTm5TZ3BRZlVtNWcwREFjU1VrQWdxT0JFCmFlZ2ZSSUtYU3h2a0VXNUdHVDhs
            dE9WTFBmcEpxYTNHMXArWUkxdzU5cncKLS0tIHhMQ1N5bjNoRzBOOFZYZUxmOUsv
            Um9RYlpMUnlYYkFvR2JnSzhUZFZabUUKYGylLmXaM2ZlowBaRVAXw5Bem7J7ZNh6
            +HpMy83kP1Hpet7eGIPTaBjHwJcTS9GIRanuYXqnzLtosp58Jszhkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVVNpNElKYnFzZFpkVzZw
            SmRWN3BTQWFLbXFPVndQUmthR28zdE93WUNZCjZXVDNka0h2NEwzTHBIT3J6T3Jh
            Tm5aMTNwckRSZXZ2Z3IrKzc4dExUZncKLS0tIERHZmdQb29SNTV2QTh1TEtlck1S
            YnB2L3FzalBxSlBucWdWRCsrMkpvYmcKax4DAibDfPd4neVNrdiNt0R6cajSPXp5
            oyKLodWWUbiertLvGE1od0WV88BSdhGHxEcL0FAvzsrmcyoaECkqDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVUw0OWptL1FZem45VFF4
            dmJwTzE2bU4wR1JiZHlJR1ZzRGN3U1B6bUVrCkFQTjNPdnVCb1hVRUpwY3U2bWJI
            dTk2WjhLKzlFYXQwbVFONGtzMGtJNVEKLS0tIEk5Y3VIYnR3elBmNVIrZWRhSnpt
            SzhpWGt5LzNRTlFKUWJOT3REMmFkNEkKE4nDjlT/9aijLlzyGTB5J0EPHQeRH4ob
            Sv5r85+FnrZir34RQxR5bXuDpbG+veUg865zPIRVtpV4A3hY5cR28w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-09T10:57:37Z"
    mac: ENC[AES256_GCM,data:TWPIycy9VVMoY+U7oicFyzWKb6UJhwV1VWPjha1H3j3p37KesLz2NnRUSItG7oBHgef7ERdQlmDie+RO5M3eyVLsRHe6Pgq06OG9YpByi6ylNeH+ezP5diECVXiXOygoqQJP0hi4zinAil/eIJ7Jsj7Ew89AUdkLphTXuP2+6mk=,iv:9edNltPsx45sWwxhGhYfLYxf6nLJ6jUYuK3Oseu3fho=,tag:9wn1sIo7FDs/aeITYXChPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
