apiVersion: v1
kind: Secret
metadata:
    name: backup-bucket-credentials
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:TUkw6adnCpGmuyDARoV4rx8LH9n28HVyXg==,iv:6qLh57SGyQopwfxGoXZz6XqEJL1StFPWn+ekfo/uGTk=,tag:n2OETzuLDLBX/bLoL9Z9nw==,type:str]
    access-key-secret: ENC[AES256_GCM,data:9gfZK6Ei4By0lUQ0b+3A2KUq67Zna3lcbNSb729RWw==,iv:Opv1BafROzdR+NpRbvS4sy6oGdQOkuBdcywe6o+zG64=,tag:lDGlTfyUu98I0Z0Qhb/S/w==,type:str]
    password: ENC[AES256_GCM,data:zdA3w873CKeM8Ya9S93NIXXw0MmUOSNGHLTrOwGX9ss=,iv:ojxfVvOHy2CtobTNKwuE6R6QZ5AE9CuEnC+ysOL4Lk8=,tag:/4ygEAP9j7smvK5Vlf3EXQ==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZHRWZHlTN3E5clliMGF2
            d0RwL3IrMmNkRGx4ak5rYmRtVkZ4K3oxT0JvClNlZUdmUmlqbTdlTi8rVVhKK0Y3
            dkVGeXRiVVV3UldYU1R4QTEyQm1OckEKLS0tIEt0c0VzcWVTL0tOL1NYQ09oelVL
            SHVuYnN3REFaK3F0bnUweU4yTDNMeUkKdT4NDCQR/OSW7bRbYhdADPYB+TtnriCK
            G8/CKqCEN+muX8K0S/THjXByrBq5jcnpFzYDJY2M3bJ9aM025PmSXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd3JSVmlXZjltNVp4ckdr
            WThvUjZlTXVKMFdxQVpNbzVJVWtvWk5BRlNBCjFGdzVQU2NNTFo4NGQxYUdpYjBV
            bDR5NUwzQUxPQ0RBSFpnZXJFdTdnR00KLS0tIGRFTlNnaHYxczN3azdZcE5wbFJh
            VTh3L25xalN6ZDJjUVZpRzd6WWhGVmMKQ2ieCwcicLaFXgT9EwETzlWjFVri6UtM
            10/P32T+ImRP/gi6GggDrI/CdKymvyhyTP89wWd0kHzaVTVnMtTqHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUGlqa0txZmY4eXR5WVc0
            WlR6OGxtWXUyMFBVaWJtMkdwbzFMQkhyMTM0Ckd0Nkd5TGM1b1E2U2lmMTZia0NB
            RG5Oc1gxaVBBc0RlZU1seDh3QnQ5eG8KLS0tIElGQXpPdmplSWV2dGtBYWxIRVRF
            QU9ITzFIS2NZNW5ZR0xONW81dDFGOGsKcKg6KR1hFEvMPx+UMJrRSHDM2mq1gjCR
            sEShR0xuJgjbFe3Qa4RO7UK1uFVllT5s57vYOxv8NtAbNuqaaqf+Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T15:36:23Z"
    mac: ENC[AES256_GCM,data:xBSpdXPsS0FlIaXxi3MtBDhdhFBBcQn+cyLAOuf/bXflaNyz+yY6saRtfxe7HrgFICqJsBan1IG5hjj8iTV5kZn1/DvIaSbXQFZJpvzj91PS95VThE+qbazrEyPGzyjmiuOZrtNbje9+FiMcYUGgNwGth3odJQQZNSq4bii+sDc=,iv:Pbma6Mf5/eiyh0aNpBgKb4EQo57uqMImrLqiIgvq+7U=,tag:cJ+m8eAy6A6OBXpLVN7eMw==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
