apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup.yaml
  - deployment.yaml
  - httproute.yaml
  - paperless-ai-deployment.yaml
  - pg.yaml
  - pvc.yaml
generators:
  - secret-generator.yaml