apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-oidc
    namespace: paperless-ngx
type: Opaque
stringData:
    socialaccount_providers: ENC[AES256_GCM,data:l67yFXXlMZq3SVaQFD2iK+4lzLNDG7YBn+zRVP7eGfcob7cqFs7zQCEzt4I4Krj1rdg6bV1hbTzYEw6FZ151gaxW955efSD7elsHZf1IAzEJ/MZ9m4TP+3IBZTVSzQ0z8+9AKn00cccreUZspSmIXBfCfEfbZuCno9eTxL0OeSzMV+CqNwC7p9JJsaNZoLXvMnvaI9ZAB0MuVW3wHjjsQsjrTEg9S4lP0mkmU98soMtvRmKuFJUt60zaj5oluinRtVJf8qK/up0s0CwsfdfvRgE82oPHCJseb1OP/6WSbx3ug3mpUcc6TyfB1HOHEGDnKmHlAeYAymowQs3W53JFzc9bxLBHQnh4iLsGJ5+sF4K71Mxo97zyiMfu+Qp8rrYiRUgMVlsVQlOlpepCnksby0cfq0Q0O+CNDYsZKpK1i7DgAzDGyjn+UeVm2Uap+O96BmQYxnOLEXoCPlt/BWg+vs/ucMgQVb27I2fPCP3J+UeiKwDtOJrh0j093dvPZrSzsZ9vTQozHk0UZtrWk0QWwJKkU+0=,iv:XjjEAn/bJkfSvYrY+VnmRrO1TY5gtF4ECa18f/LL+m8=,tag:znKUZH9S/o/winmTdDr8EA==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVlI3eVd5Q2ZoL094aUhp
            ditLTjZhNGNoZ0l5M3VnZTdKeEVMaG4wMmdBCkpveDdBSHFSUlFIcnl4YUZrdk5m
            T0Q1OUUzOU5hTXB1WmZ0UCtPYVVockUKLS0tIGVBcEVNUm0xZDZlREFVT0NRMmhT
            bnRoVVZRVTZJak42Y3RZVnV3OGRKMVkK9Rk5ZLaJFv4f3mY7E5M71U+Rth5hPjoz
            +iTsYvYvFB5ReILHFKJBrYRvQ5zLUXw3IiHcc2WE+5L68+rAIWgfKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUK1hCQTlZTmNjY0FHdG5W
            ejhCelZQZ3BUdTRIOGViaVVjWWRzeE0yazFvCkd3cVdUMjd1RGV6djlJVW9qMGtj
            Z2R5b1FOdXQyWUtKbVBxclZkQUszU1kKLS0tIDJyYzBDczZYMmhmOCtpSG91eEE1
            dHAxT1RZNzdCWVpzU1EwWnBaVDJHZWsKejjXJI8jX4msoguZlnD8XhyLJhA7CRy7
            N28+8H9EvnapHkYYEfHlHJP1fQOqPj5himaFQ5o4BLcW2EILr4CLcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRWZ2MmJSeVJMR1A1U21s
            YWhFeXpSMGtDcE9kSHdTSk1PMzlCQ2VVQWkwClNWMmZVRFU4WFptRDZEbXpUZlJz
            UlZiT1VHd2svV1FVWkZFcW43U2poaDQKLS0tIEl2a3hLQzhCMzU5RDBsUllpc014
            OVc1NGNjemZCcXN0Sld0QVp1dGl2SUEKNNdrOuoR7WOvyXdXQD80g/ZuWQX13dPp
            TkGH4crft043a+86cV+RuoiSGMkMfTn7OkCxSOY1oOKPW9E/PVB5Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T16:01:07Z"
    mac: ENC[AES256_GCM,data:odR7zuMfFN0QVzWCiJS6TX3obo40+GNN/DbCFIIZs99xm/Q7pl4+3oyshl/8XpPUJrC3MSyGz/ba4holKDiHh8Z4qXTYzRnSoKjWtfARNvY8N2k0kCO71tQkGnldb4+oBUk+ROeXaP9TZhBKY9mVnAtyaE8Y6b/y+e+Zr58dvJc=,iv:Mv4rk97uLHUrW1FMyfWcPIcOlc30B2jijOgkGZ1LMsA=,tag:HnVu5oSBrvKQeIFWMr+yHg==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
