apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-oidc
    namespace: paperless-ngx
type: Opaque
stringData:
    oidc-config: ENC[AES256_GCM,data:bclQOl3/WORMHOUiH2uRWYO9l3Q3a1WSO9gXg7PgqkJgp1MdkXwro+2bZSYoDMuTBgOHcXmowD36KoLhEFE0IJrov+HfCrgaEsvLhg4OveG0eb2iXzzlwcydyChnabyEn2hW9mB0fFx8TPGX8o8p9naoHeXy8m9MgAygk9WU6ZqPGEJF3ZsJTWQFtzY5/kK0ekMM3TqBnWQDMwsxDPhPSaWtTA5agyyxyxW9HLY87qKA7kjHwIjSjSMwOS8v5hqTJTBBw+Snh5U3UYeEUAY/AvglyHpOoVJqmP36SmeGe8RSKCVPbGyDvL3EAadQTNzGmItFJame/0CpNcXL0sd1NvbZ9zlQp6Rbtr5Hbfcsmpy1RXCdpGrHLLVKV+Wg4TJhBrR7vzwksTHh8h0EByLLWkYG+17QUPk0TufmT5+GS5dH4wJkn6vxeq7BlCG9tffY0KbsHkkn8RZyRDmYYj9tn4sRbI5nqnDLwHw8w8LS3ODK45fuNYZKTZsB4FZXg2xMBJvTBRbm8jMvHAmTsrk0XDYjs9rQ99Y=,iv:nhAlYPCa0kjIObC1Ce0OJL+wEMr4ZiSbcuXScW3PXcw=,tag:WT1+P3WWgZqlE4UOISiM1Q==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVlI3eVd5Q2ZoL094aUhp
            ditLTjZhNGNoZ0l5M3VnZTdKeEVMaG4wMmdBCkpveDdBSHFSUlFIcnl4YUZrdk5m
            T0Q1OUUzOU5hTXB1WmZ0UCtPYVVockUKLS0tIGVBcEVNUm0xZDZlREFVT0NRMmhT
            bnRoVVZRVTZJak42Y3RZVnV3OGRKMVkK9Rk5ZLaJFv4f3mY7E5M71U+Rth5hPjoz
            +iTsYvYvFB5ReILHFKJBrYRvQ5zLUXw3IiHcc2WE+5L68+rAIWgfKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUK1hCQTlZTmNjY0FHdG5W
            ejhCelZQZ3BUdTRIOGViaVVjWWRzeE0yazFvCkd3cVdUMjd1RGV6djlJVW9qMGtj
            Z2R5b1FOdXQyWUtKbVBxclZkQUszU1kKLS0tIDJyYzBDczZYMmhmOCtpSG91eEE1
            dHAxT1RZNzdCWVpzU1EwWnBaVDJHZWsKejjXJI8jX4msoguZlnD8XhyLJhA7CRy7
            N28+8H9EvnapHkYYEfHlHJP1fQOqPj5himaFQ5o4BLcW2EILr4CLcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRWZ2MmJSeVJMR1A1U21s
            YWhFeXpSMGtDcE9kSHdTSk1PMzlCQ2VVQWkwClNWMmZVRFU4WFptRDZEbXpUZlJz
            UlZiT1VHd2svV1FVWkZFcW43U2poaDQKLS0tIEl2a3hLQzhCMzU5RDBsUllpc014
            OVc1NGNjemZCcXN0Sld0QVp1dGl2SUEKNNdrOuoR7WOvyXdXQD80g/ZuWQX13dPp
            TkGH4crft043a+86cV+RuoiSGMkMfTn7OkCxSOY1oOKPW9E/PVB5Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T16:23:10Z"
    mac: ENC[AES256_GCM,data:EErbevZEfB2fMnoM+5KUoI0XXoDsXl4CMt7rBVDrojStucylta3KBOoSti42G97tJf7UBJIlifxxodjcELGERAv1vArS410YYwSEUvqd82uQhZroUjXhrpAmh4K5YD0bs4qv1wVnzhWRt7CiZUL9TDfkp49OFYUHPPqcERibhbE=,iv:h1l0y2gEENLjZyL+pr9uxmDLXE8eSmxIZl74uKnmqmw=,tag:yNHaA6K8CRSCnP8IyHHXrQ==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
