apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-admin
    namespace: paperless-ngx
stringData:
    username: ENC[AES256_GCM,data:qjahsfo=,iv:+/WNwIWlT0ugCLKXpRrYAXy2Upk1j8tyMiNwUNfxlrg=,tag:+4Kg+ySWHZU2BbKJRJHwhQ==,type:str]
    password: ENC[AES256_GCM,data:XF0LXooOTzJ+dot3ko8o3JJFiFytqwlOsLR8U+oP0bk=,iv:2/knHGcdCBdk9qUhtRa2wtki16WpJJzVJrumwYCjKHk=,tag:d1vMQnQtpAfjI2tLlMISng==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOWxSay8zbkd2Q1grVWFQ
            elNtM2VjVHFadkxxWmVnUU5MRXZyVVhRRGkwCkVueGR4NzhoUDBRUDVEQXZnUTZy
            NW9SbFIxL0c0a2pZejZIMEMyZ3hYaXMKLS0tIEZHemtPN3dJaDB4QytNc3NLVDBi
            bVRPWlJQbUV0VWNGSHZjRWZ0MWFFSTgKBCr2A8UyB4mOLqZ6PDKI+8mlkWyCGSQ4
            M/niV5gke2/IUX7mok3/AL0y1n9eAGS4z+S+nTJ/b5gTuQ+pyr8jrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZzNialJzZSsvc0oyWmxN
            SC9vSEEvL2JURFV5bmNMNXp0OElTeVdtM3pJCms3OHdQSjVBcFRXTUg1VzFFcjh0
            UnlHS0ttdnA2VzZrZjZOWDhzenhxbG8KLS0tIDhaaG9FMmwzdEZ0VzN5QU94SUNF
            REwyY2J5Z3BXMUhtaG9vMTRmYTFrd28KT1Dmx+m5dueUKZKrtmemn0Ok4eHMsTlk
            TEdsERJWtFkBRDnapJFiF5s6YpGNMKHcAK0SFl7++8Ckr7yp5qcSZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMFNYU0o3OTdoSFhwOGNr
            ZS92MVFrY3pQN2E2N3NYMm1US3crYVdTaDFZCmJVaWsyT2hnREJoQUNjV05Ib1c1
            MGRwam9RQlRGSTNBS0c1SlgzOFZNVmMKLS0tIHZTTFdweExRbTdadURjb0FpT0sr
            ZzJOQkE0UnZQbUJLd2ZJTjZKbnZwVU0KflJCvZFQt5m90Ddx9saNcwJvti7b4gqx
            Qe3P5WQXESJoBaYkZU9pVnoLv1kdI+BJLtqp1q6L3tWyC6zYG3hq5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T15:43:14Z"
    mac: ENC[AES256_GCM,data:KvxAsAgSxOKY+mmEDy9vGLMiNmNoal9Xp57eyBp7/fY3A47Ehb5ka16+eMbLhhQ3oIkMoz4Q6uJifYz+Vzr9UgLjWtbu5mZI4VjrmCRg6/lgMjgnQuEe920C1IID5cqnYrdSvRXQf3r/aXNup4yoChErV6Z5GWh8slxWirWJqzU=,iv:hLTq1hUsScYj/37QBRVgeEVGQwd1y9X6BzLhv0Pr5/Q=,tag:jgamc+5UmZBV4XtyN+XxTw==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
