apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: paperless-ngx-secrets
files:
  - backup-credentials-secret.sops.yaml
  - paperless-ngx-postgres-user.sops.yaml
  - paperless-ngx-admin.sops.yaml
