apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hsts-headers
spec:
  headers:
    #HSTS
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    forcestsheader: true
    # Other security stuff
    framedeny: true
    contenttypenosniff: true
    browserxssfilter: true
    referrerpolicy: same-origin
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https-nonpermanent
spec:
  redirectScheme:
    scheme: https
    permanent: false

