apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8up
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - path: manifests/apps/talos/_system/k8up
      repoURL: https://github.com/TheBigLee/talos.git
      targetRevision: HEAD
    - chart: k8up
      repoURL: https://k8up-io.github.io/k8up
      targetRevision: 4.8.6
      helm:
        values: |
          k8up:
            envVars:
              - name: BACKUP_GLOBALACCESSKEYID
                valueFrom:
                  secretKeyRef:
                    name: global-s3-credentials
                    key: access-key-id
              - name: BACKUP_GLOBALSECRETACCESSKEY
                valueFrom:
                  secretKeyRef:
                    name: global-s3-credentials
                    key: access-key-secret
              - name: BACKUP_GLOBALREPOPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: global-backup-secret
                    key: secret
              - name: BACKUP_GLOBALS3ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: global-s3-credentials
                    key: endpoint
              - name: BACKUP_GLOBALS3BUCKET
                valueFrom:
                  secretKeyRef:
                    name: global-s3-credentials
                    key: bucket
              - name: BACKUP_PROMURL
                value: pushgateway.k8up.svc:9091
          metrics:
            serviceMonitor:
              enabled: false
  destination:
    namespace: k8up
    server: https://kubernetes.default.svc
  project: system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
