apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-system
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-kube-system'
    spec:
      project: system
      source:
        path: 'manifests/apps/common/kube-system'
        repoURL: https://github.com/TheBigLee/talos.git
        targetRevision: HEAD
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          selfHeal: false
        automated:
          prune: true
