apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
stringData:
    GF_AUTH_GENERIC_OAUTH_ENABLED: ENC[AES256_GCM,data:W3p64w==,iv:Ol9h0hpeL9OqXQMBGTbr2VckmVunvI0dQfsP17+ozpo=,tag:csKlgTNUV8T//lO6J9WYtg==,type:bool]
    GF_AUTH_GENERIC_OAUTH_NAME: ENC[AES256_GCM,data:ObLwQHpI/A==,iv:4ta9b8ZpHMRcx0UmVBDBEPbeyAu5ffeSzeEkjQCQTu4=,tag:/vPeeO+ELbGA6Pd+FWZA/g==,type:str]
    GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: ENC[AES256_GCM,data:FFwSbZY=,iv:i6cWqC6UQIFEpWDikBgsronLhgvjec1TTxVKcq17NNg=,tag:FpN1/BF5WuzcxPQiuG/kxw==,type:bool]
    GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: ENC[AES256_GCM,data:seQPeQ==,iv:HgDYp0EDjtHugT9N+AERf3suX2oShXFR1uymhzWpOWQ=,tag:OV/ldmK/G9Ou0Of1lunTuA==,type:bool]
    GF_AUTH_GENERIC_OAUTH_USE_PKCE: ENC[AES256_GCM,data:O9sOIA==,iv:pXEnfOW+lpC+Tzasi47xspaccCNkY7OPgtlDcR2xy7o=,tag:ZZT+2yYQ9NY31DYoBb35Ug==,type:bool]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Yhw8UbaqHxKcdV9HgFgNxL9v,iv:eKf0Lv0fJ3FePIpaLzsZPKgZf8Z23brw0NURF2muHf8=,tag:IJzPw/MRKL9PVpl/W+u5bA==,type:int]
    GF_AUTH_GENERIC_OAUTH_USE_REFRESH_TOKEN: ENC[AES256_GCM,data:DcnpYg==,iv:xA5mI+D777wbnHy02C1hJT/CuoD0oNzJlVF2tZEI8lY=,tag:OS5OoI0bkJRyChw+TyEJ6g==,type:bool]
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:U0K+fPlW6vFvkvy5XUV8cAQHaTa3Il5LTmvFYo1NGw7hMYHMsXzX,iv:X1DQZkeWbakM09/R2fdtYGZMwhmhSngEnEq9542DMuw=,tag:CAL8eGfvInJRCarJ6+FOIg==,type:str]
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:GK3aYm5qcgHZZLq81gUxjSU6HRmM/FGia2aHvPDi3SQrSbk=,iv:xdyWIEbxzPolPxXGOEkHcY7sV9ut4mATivt1Tjvmo8Q=,tag:G9MM4IFlpeuhpOOa2t1seQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:lk9YK1DD1tY7+LEiqa+NjP14BUMLReNlq1qKaTfZ15ifzUmcDw==,iv:aYneaFj0SCOZF72GlfjQs4Z4k80RrVHfbVCkPBXCXis=,tag:UHXixgDYGnM4VtCthByduw==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWGZnck9qVGlmRGRBNmx5
            b2Zydng2SUowT04vS0c3OGN5dFpGK0hwcVJnCmZXRzYwcDlTQWxyeHhHRFJ6RXds
            TkpnVVEvNEovc1lDdE1Fak1Pek1wb2cKLS0tIHNmZ3ZVWHl0SVRoRXdkdW84TzBs
            NWtQelBmMWp1b0F1ZzJYTXNlUU1QbjgKnwfI2/ywjpAgW5es0a37CK113svAVwiY
            uYI9nhUHSiJ4A9c6jEJmgyRhl9JZnNrp4AivUKl12/ouL15d0jG1ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RUVQaVVLejVKMXF6MGxp
            Mk9UTTdQQWJUanA1NlFoQzlPaEpEWGVLZGhrCi91THd1cS9mK1J2S2NVZS9OaGJx
            dHRFdURxK0ZsRFV4MGR3ekN4ckNwaVkKLS0tIEc1aXhMVFdmak5hZ1ZHNTdjVm1O
            T0JyRzUraG5ZeExYQWxFd0cwaTBoMXcKxUrDCi7mwV+JC7Y5OksOVdhjJPgipw2a
            RGSSgPdZBxlcoXIyNEZLtfNXdYF7KG9VZw0T8To9c1U9mEWgodUApw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdldWUXRxV3BNcWpkZE9m
            akM3SEszNHZYYXpWakowZDN6cmt1VTA0OWhFCnFlcWhXampkME1vMlNWZjRCelha
            Mk5VdGFJSlI5SGpwcXdTMUpXVDhWVGMKLS0tIFFtK1FPeXRyaTRjNVRlSTVnQ08v
            akpia2JMUnFWc3pVWmYrT3c3RjhucE0KmOQjMsezLi5idsrlJJG0QFS7z+7bn2y4
            VrmrhnOZPxiHLNDcequohuXMhppggLv8OkEMDtE7qSQ2ZeOWi4ELtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T17:45:15Z"
    mac: ENC[AES256_GCM,data:fK+k3LTBe9zJY9iIEvANRkOwnaERPpfGWCfl+HxiPb0Jo8alIXkCQh8La1OTxldq2pxa78bEMbm6ZUhzpt+iR+Fw9ay/INRXAfZNMH3ZmpS9c2ULvZB3PdnQFWPeJXXwFSOI5roMxFFPi7EgIKTvdeDeH248SNm/OE3+4au/7r0=,iv:PFCJ/Q2o0xj9N7smlTPqD55sTldaX2LM/KpewX3EojM=,tag:+fKKCdkd8yflwMq3AHYvFw==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
