apiVersion: v1
kind: Secret
metadata:
    name: admin-creds
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:1OiSR3c=,iv:z2o62yxODC+5KRvebFxMjweMUT3gBA5MsMrjTcLZFMM=,tag:gCsPpcF4CRBqStNFnK1Cmw==,type:str]
    admin-password: ENC[AES256_GCM,data:qK+fl6+8KUr+r38J/W0/1bT8aEbjFApWqFLUqCgEvnA=,iv:oKLrmjYgYNETMOWFr3Ah2N8zbbHkzxfoBz56/ODQjKg=,tag:IWLxl4GZR/Xec9gZ7Poj9Q==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOSsvamhtVFIxZ3dZVlJO
            Njh3MzdVQ3BxTzRIZlJlVWlCd2ZoMHBsZTFVCnJvQkpWd2NmbFZPZFZMSk9WNXlJ
            VVFCdjFJRlFVTlBVMFNObGxiRWkxT2MKLS0tIC93cWNlNmdvdDFNQUpjUnZLUUJs
            alRNaE9TOG9Kb3BVcGVYQitKcWVrcGsKYJfWDqjhrMH/7IUXuXBH5dsZEF971jpN
            WkvXOQbZakzMvducC3TV3T4bMJE1RoJXSRLDPyFJPiizi30kVZGNXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbVlBaTlZUUhubzlqR2xu
            VGQzMlRPRFNBM1hzeSt3aERKMk01YlM1U0Z3CkVNY05vYnNPc2pMV2kreUFsQ2ZY
            SWxVU3ZadHRCWkFJOHVyR3hCVkdoM3cKLS0tIEQrcGdEY0dFVW9QSTdEY3B1NUlX
            TzFxWWNtUWJIRWNBUVV4ekI4M0E2UlEK+vUUPE6gJFRMd/4DoCTRzbJK+sD2DaK7
            YwoHMAJZxKW3ZmhWCN6RN/Pa1puwD3XuYfKD3L+XB+AXZynObmMlrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV093MFpOaGsrcUdsTGNx
            cHNwbWpVYWtYd2NQbm9yUXVHMU1WOFlXaVVNClVJNGZxQTNUZkxYTjlTdXorN2dQ
            b1ZQQzNYY1lWZzgxTnBKbCtOTjVvWGMKLS0tIGoyTE1icGlLd3RMU0xrNjdLZkw3
            ZlE4bHh0K2I4MDdKWHovNUMrdStXNncKNDy+4uhBQlMC3gReueeyfft/NRlR5kPq
            +pM53KfeT+SPiX/Rz7/isBsi8rfeJKGwlG9gvbwfnrsQiWrLIO4Bow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-09T10:51:52Z"
    mac: ENC[AES256_GCM,data:+144Ls0BgtQYOW+loIwr9+XkQYCq8ijy9InD+QLVFGl8IySH5ZHMpPUbtQwcYbt36pj+MffsZ14ymyHCq9iUbebQNmFm8xgD5xnjp0X3HWDwfNemOeZ6UVAZvEE2B5YhmT7MaVOMktjJEnT/iXCZFv9MRoP0tyrjhHMCJa08XNY=,iv:m5m2Pf0Zoy5pcDXpIH9IaHi4gKhuqP+XZUoaYVqd7hE=,tag:+IYgOd4Tpa5EVH/uebO8PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
