apiVersion: v1
kind: Secret
metadata:
    name: zitadel
type: Opaque
stringData:
    masterKey: ENC[AES256_GCM,data:hk3fTcATMCoBcOusQUKRtFcYK0o1cZ5lWkKcMiC4OfI=,iv:TRBMdIEkk4Ya6DsId3YjpBQVPgrZynGkh1Z1Z7KgHx8=,tag:+HaEcFTfApdrbcQ7k8MsFg==,type:str]
    config: ENC[AES256_GCM,data:nOtTaO4SOqFGDN8vNxNNdFRef2wTJAEiNo5FskmWmtfTCxQOGlxLq+8urNUqg9802jTZmZBZM7cp8IcW+DEHfuNE0MIJeANrjqOoldMCL94SEcfd9WM6+5LL57KuBhKYQUxhKe9fpFQf77IKva7J9evArfw8dB8wm+UV3GNSQzAdEOPY7S5spJUzj1ICMlffiwJ0R7EjR6T3,iv:ZZQuP4MilUWfU5G4sNaGq2IW8kmfpN4LGPXIpXhHZfA=,tag:986hvxW1kRiORnea+V6QJQ==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNEtEZ2xhU1NPMkRNT2py
            WDJoWTVDOXJXUHMzV3pFaXg2dkE1S2U1eml3ClVhMmR2T0RBY0RJYkVuOXdDdjRG
            OUxXa0xhSzdHaWVIWWJ0Rk9JU1RVM28KLS0tIGtVd2ZKU1g0Kzhvb1h6WU9KUW90
            UXNPUkcyVm5JdXFlbi9tQTcwY2ZvYjgKFcfQ5Whgs5YkX81XLIdpwG9/Ne0VqtZe
            2Wk3ywPeH+NJARe9kogWuphoc+9qPZ0g2Qw8B2pC+a/AvOZdajOt1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZnNkTUxiSnNXa0ZQekNh
            OGZJaUFkQS9CcTVHWktPSWtTeVNTenBoOFVJCjBZWFkvcmR5Ti8yLzlFWW8ySXUv
            V1ZlajlNeVRrQnV1bnBVQjhyNmVSd3MKLS0tIGltV2E0VWVWR1BxOHZaRnZCR1ox
            ZDFiVmliSFg4YzVQQk9vS0c1REdpZFUKYoyShrvL/jN5uPCnsTKCDFR9OmEEiEyO
            ER2Q2NfXyucrlEekJq0jvWmdMzSfOoNN8IEd51SJyybBs7dwD7n2BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSzk0UU8zbUIwQVJvdTd1
            US9sekRpdkF5WXJEUHl5YW5nNXRUTzFaV2lJCndiSHVHNTFXZ2d6NlFwU0oyeFky
            SGhjTnFLc2hIREtmV1paa1NJYmxRa28KLS0tIHFpVzBPMzloZVBhSmpwWmJCa2xs
            VDlCY3VoUU5ydW42ckhYMGU3a21NYWsKpn5asGM3awyCCJdlobcTmaKWdFRI1MOb
            PZ8N7eR9hZqKQfOWq5BFU7j+UQhnGTa7/6Cmfd6PFZZwvbbtyenDeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T10:02:11Z"
    mac: ENC[AES256_GCM,data:NRSR4+9ODjZb6+MWh4MIp+M3Gk8B0OryU2xqufrRtS1aGbrdeSYhSwojU9FsyYF5r4kwm454BX95JFBLbqdMeaw617Y6prBv2vuylUE1BSGPq9r11VrXXUEl9XUg8ji9T6Z6uKEFj3iW4FXUwzhLHd0DAjK/qd3lE51sLZLaWyE=,iv:NYDP5q/WWL/m5Ra9KYoEls/1h2RN674xkrPU8G4O8wE=,tag:1huBNLK7/dQkWJEQcZ5fng==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
