apiVersion: v1
kind: Secret
metadata:
    name: zitadel
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:0AP3P0Qs+IxTukDfxrrK2lqhRVKs6sTbBc4I8UwB2xY=,iv:faUM+3SaGeuUIgVlnJP5Ca8rBkb4z787XboTMCox4Ok=,tag:d69iIWp0Yq6wFFldQKjb/A==,type:str]
    config: ENC[AES256_GCM,data:BvxpWDUzMAowykUITo8ShbcsPD2vU1bCk6LKrAueBlQaPMb7zzWYkh/XBm5J+6+J5ORC9iVo2teCTEUhYmUxfhVbMCjsU73SWrn2DPAST52jb0NQsAcY/rx3pAa6RCNZaTFJZtcpeJ3oFOECWY6Qnp2PzDp7LXiRPvGGNbWfTjxMkQP9IdqEEp0bEg5JsM2ArnfTM1ZtkGPLAGIdwL/ZcIc4I3bD4c6VXD40M1s=,iv:lvKZEOVEwCTCAC+lQzP8Z0MSv8ZPpHzoHkJzxSBmVrQ=,tag:IP3C1Y2zPZYveEMMaVBXKg==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNEtEZ2xhU1NPMkRNT2py
            WDJoWTVDOXJXUHMzV3pFaXg2dkE1S2U1eml3ClVhMmR2T0RBY0RJYkVuOXdDdjRG
            OUxXa0xhSzdHaWVIWWJ0Rk9JU1RVM28KLS0tIGtVd2ZKU1g0Kzhvb1h6WU9KUW90
            UXNPUkcyVm5JdXFlbi9tQTcwY2ZvYjgKFcfQ5Whgs5YkX81XLIdpwG9/Ne0VqtZe
            2Wk3ywPeH+NJARe9kogWuphoc+9qPZ0g2Qw8B2pC+a/AvOZdajOt1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZnNkTUxiSnNXa0ZQekNh
            OGZJaUFkQS9CcTVHWktPSWtTeVNTenBoOFVJCjBZWFkvcmR5Ti8yLzlFWW8ySXUv
            V1ZlajlNeVRrQnV1bnBVQjhyNmVSd3MKLS0tIGltV2E0VWVWR1BxOHZaRnZCR1ox
            ZDFiVmliSFg4YzVQQk9vS0c1REdpZFUKYoyShrvL/jN5uPCnsTKCDFR9OmEEiEyO
            ER2Q2NfXyucrlEekJq0jvWmdMzSfOoNN8IEd51SJyybBs7dwD7n2BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSzk0UU8zbUIwQVJvdTd1
            US9sekRpdkF5WXJEUHl5YW5nNXRUTzFaV2lJCndiSHVHNTFXZ2d6NlFwU0oyeFky
            SGhjTnFLc2hIREtmV1paa1NJYmxRa28KLS0tIHFpVzBPMzloZVBhSmpwWmJCa2xs
            VDlCY3VoUU5ydW42ckhYMGU3a21NYWsKpn5asGM3awyCCJdlobcTmaKWdFRI1MOb
            PZ8N7eR9hZqKQfOWq5BFU7j+UQhnGTa7/6Cmfd6PFZZwvbbtyenDeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T10:27:28Z"
    mac: ENC[AES256_GCM,data:T9p7QXJFMN5NZ9DjawlFHqSIN/AS2jwFGailBtVTpZBxU9BLoDcR5dkUGBLjydUe0eP1Z3btwffZ5nSIMz7FI3eH1sTMGzoM0e4xTNNVlaghTaCn4vjh7trSOb4P9f5U2Z8jviq2EhsOus0E2RjFmd5YzdgAt1iBH7m/lPE+wyo=,iv:XsQZHp6/Y/lTP9MG4lKvwhKKB21hANC9v2ZBZUM2aTY=,tag:V9E6gEj8DZaNnMk0+YJCOA==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
