apiVersion: v1
kind: Secret
metadata:
    name: zitadel
type: Opaque
stringData:
    masterKey: ENC[AES256_GCM,data:hk3fTcATMCoBcOusQUKRtFcYK0o1cZ5lWkKcMiC4OfI=,iv:TRBMdIEkk4Ya6DsId3YjpBQVPgrZynGkh1Z1Z7KgHx8=,tag:+HaEcFTfApdrbcQ7k8MsFg==,type:str]
    config: ENC[AES256_GCM,data:imou2CMpwf2/ItNd3hCYUgH3KuajXM19QlSgMhysM6SWi8bqc7lM0NKrPKTVMUT9oe2NwoZWkLnn5TGMxmDPPr3fuBMhTm36UDm4h7zcUCmB68kWz7rTgL5MTm5yE8KJ3Cr/9rsHiPHnigbvXynwWD56Ms+LAe8mEfPhebOqhFOw5bKzdMiaiWohxG4NO54U1yFoZH0TVA1Zcs4H6BlNFvCI+XSjnQgA0lRPCZ8=,iv:YS6RCWhw2zzLXoWUrpxkcs0p6vyYgLF0112eABHZ5wo=,tag:fwDS/sZbKSo4eHlgv8IGoQ==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNEtEZ2xhU1NPMkRNT2py
            WDJoWTVDOXJXUHMzV3pFaXg2dkE1S2U1eml3ClVhMmR2T0RBY0RJYkVuOXdDdjRG
            OUxXa0xhSzdHaWVIWWJ0Rk9JU1RVM28KLS0tIGtVd2ZKU1g0Kzhvb1h6WU9KUW90
            UXNPUkcyVm5JdXFlbi9tQTcwY2ZvYjgKFcfQ5Whgs5YkX81XLIdpwG9/Ne0VqtZe
            2Wk3ywPeH+NJARe9kogWuphoc+9qPZ0g2Qw8B2pC+a/AvOZdajOt1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZnNkTUxiSnNXa0ZQekNh
            OGZJaUFkQS9CcTVHWktPSWtTeVNTenBoOFVJCjBZWFkvcmR5Ti8yLzlFWW8ySXUv
            V1ZlajlNeVRrQnV1bnBVQjhyNmVSd3MKLS0tIGltV2E0VWVWR1BxOHZaRnZCR1ox
            ZDFiVmliSFg4YzVQQk9vS0c1REdpZFUKYoyShrvL/jN5uPCnsTKCDFR9OmEEiEyO
            ER2Q2NfXyucrlEekJq0jvWmdMzSfOoNN8IEd51SJyybBs7dwD7n2BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSzk0UU8zbUIwQVJvdTd1
            US9sekRpdkF5WXJEUHl5YW5nNXRUTzFaV2lJCndiSHVHNTFXZ2d6NlFwU0oyeFky
            SGhjTnFLc2hIREtmV1paa1NJYmxRa28KLS0tIHFpVzBPMzloZVBhSmpwWmJCa2xs
            VDlCY3VoUU5ydW42ckhYMGU3a21NYWsKpn5asGM3awyCCJdlobcTmaKWdFRI1MOb
            PZ8N7eR9hZqKQfOWq5BFU7j+UQhnGTa7/6Cmfd6PFZZwvbbtyenDeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T10:22:10Z"
    mac: ENC[AES256_GCM,data:Zc2wCyCT3KBIwQg8N2m6I8JLC/OHPo82UidXKhh2z38tbKyqKZkTcSxFhbMtTS0GftIGZh3qnQ73v0ssrE1PgSGu6U08so9mFwsuPffyBs9w2uqhZJDLzYHPhNqcBoNLctDbibnKFMKw7QcCKYRKqVvaz2MIXAZSLIriZPAl8rk=,iv:AepCdPP0SRehNm+bNa4kLC3vDLCecbtRvPqLx1EICY8=,tag:eMIMnSsH69vmyKQL4J/98g==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
