apiVersion: v1
kind: Secret
metadata:
    name: zitadel
type: Opaque
stringData:
    masterKey: ENC[AES256_GCM,data:hk3fTcATMCoBcOusQUKRtFcYK0o1cZ5lWkKcMiC4OfI=,iv:TRBMdIEkk4Ya6DsId3YjpBQVPgrZynGkh1Z1Z7KgHx8=,tag:+HaEcFTfApdrbcQ7k8MsFg==,type:str]
    config:
        Postgres:
            User:
                Password: ENC[AES256_GCM,data:ONqTRAt+UXO/0zaqPxkZT/S/vwbMZfAUeUK7AtnigSc=,iv:fhwBgImGBhRIYs3SoKWy3EtDwc4JNGlJvqNFXQ71Cls=,tag:0TF4mXQgJII9hQWAEi/F9A==,type:str]
            Admin:
                Password: ENC[AES256_GCM,data:dnjBGY6fbS0rwaDuxDnSLRUG8ULrsELA/Gp/f0FXXN7bPFLUmCY6NC/WxuZN8Ni1Z4HOhCQ5jpq+6/pxCpHgQw==,iv:igqIMRAcP5KwG6tphgh2howDis3uqfYFRd68XW9jcv8=,tag:P7vVtC6kMoS6E2oFPjG9lw==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNEtEZ2xhU1NPMkRNT2py
            WDJoWTVDOXJXUHMzV3pFaXg2dkE1S2U1eml3ClVhMmR2T0RBY0RJYkVuOXdDdjRG
            OUxXa0xhSzdHaWVIWWJ0Rk9JU1RVM28KLS0tIGtVd2ZKU1g0Kzhvb1h6WU9KUW90
            UXNPUkcyVm5JdXFlbi9tQTcwY2ZvYjgKFcfQ5Whgs5YkX81XLIdpwG9/Ne0VqtZe
            2Wk3ywPeH+NJARe9kogWuphoc+9qPZ0g2Qw8B2pC+a/AvOZdajOt1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZnNkTUxiSnNXa0ZQekNh
            OGZJaUFkQS9CcTVHWktPSWtTeVNTenBoOFVJCjBZWFkvcmR5Ti8yLzlFWW8ySXUv
            V1ZlajlNeVRrQnV1bnBVQjhyNmVSd3MKLS0tIGltV2E0VWVWR1BxOHZaRnZCR1ox
            ZDFiVmliSFg4YzVQQk9vS0c1REdpZFUKYoyShrvL/jN5uPCnsTKCDFR9OmEEiEyO
            ER2Q2NfXyucrlEekJq0jvWmdMzSfOoNN8IEd51SJyybBs7dwD7n2BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSzk0UU8zbUIwQVJvdTd1
            US9sekRpdkF5WXJEUHl5YW5nNXRUTzFaV2lJCndiSHVHNTFXZ2d6NlFwU0oyeFky
            SGhjTnFLc2hIREtmV1paa1NJYmxRa28KLS0tIHFpVzBPMzloZVBhSmpwWmJCa2xs
            VDlCY3VoUU5ydW42ckhYMGU3a21NYWsKpn5asGM3awyCCJdlobcTmaKWdFRI1MOb
            PZ8N7eR9hZqKQfOWq5BFU7j+UQhnGTa7/6Cmfd6PFZZwvbbtyenDeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T09:55:24Z"
    mac: ENC[AES256_GCM,data:1VB6h/dT67sMJ0IW1cU6CK/5kXHItojoHVPj6+JBTjGiEDdcM9dkz7FO0fyWe08VM6O5TQZGjGeAO7vTW3PxLa+WnKhLjjHQ+cJL2MgYXIzQBu7vGfRFDbmo5DIV+tBeMjSpiI9JzDw1m8bYlUAyMHIL6b3JWIOXlouwQvklXOM=,iv:efbS+/dMQHD8+1YtjLx0SMcle1qfpnJeFn8zO72L+II=,tag:zt77BnAa4rKzhUqMvi7JrQ==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
