apiVersion: v1
kind: Secret
metadata:
    name: zitadel
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:0AP3P0Qs+IxTukDfxrrK2lqhRVKs6sTbBc4I8UwB2xY=,iv:faUM+3SaGeuUIgVlnJP5Ca8rBkb4z787XboTMCox4Ok=,tag:d69iIWp0Yq6wFFldQKjb/A==,type:str]
    config: ENC[AES256_GCM,data:uFpI1p6SgVDuXj8FgLKekVyFuV5dAujDzX9QhPMJBVnq7qVhfaNIbO6C/OcC1FLo5/Ce4bQ4uRHzxRqpVeRdyOkzHv1df0ms645YkEgAzOeAoU5NFzffukncQA8dWWbs01O/OCrBkrxl38aBaAKSMAAcQrBNrixfAMM0rrYeF1mQQ3qrfe42pWCuFoyPriEJ5/9cvhRn8luLOlpK3vLoth8ltL2IUgpP5gF2gqY=,iv:zhf3ikdPVkjcitHtBjGCwT1/Hh7BUceSb/R2OiSuD3c=,tag:NZVh/GoUTExrYW/OJAYcng==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNEtEZ2xhU1NPMkRNT2py
            WDJoWTVDOXJXUHMzV3pFaXg2dkE1S2U1eml3ClVhMmR2T0RBY0RJYkVuOXdDdjRG
            OUxXa0xhSzdHaWVIWWJ0Rk9JU1RVM28KLS0tIGtVd2ZKU1g0Kzhvb1h6WU9KUW90
            UXNPUkcyVm5JdXFlbi9tQTcwY2ZvYjgKFcfQ5Whgs5YkX81XLIdpwG9/Ne0VqtZe
            2Wk3ywPeH+NJARe9kogWuphoc+9qPZ0g2Qw8B2pC+a/AvOZdajOt1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZnNkTUxiSnNXa0ZQekNh
            OGZJaUFkQS9CcTVHWktPSWtTeVNTenBoOFVJCjBZWFkvcmR5Ti8yLzlFWW8ySXUv
            V1ZlajlNeVRrQnV1bnBVQjhyNmVSd3MKLS0tIGltV2E0VWVWR1BxOHZaRnZCR1ox
            ZDFiVmliSFg4YzVQQk9vS0c1REdpZFUKYoyShrvL/jN5uPCnsTKCDFR9OmEEiEyO
            ER2Q2NfXyucrlEekJq0jvWmdMzSfOoNN8IEd51SJyybBs7dwD7n2BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSzk0UU8zbUIwQVJvdTd1
            US9sekRpdkF5WXJEUHl5YW5nNXRUTzFaV2lJCndiSHVHNTFXZ2d6NlFwU0oyeFky
            SGhjTnFLc2hIREtmV1paa1NJYmxRa28KLS0tIHFpVzBPMzloZVBhSmpwWmJCa2xs
            VDlCY3VoUU5ydW42ckhYMGU3a21NYWsKpn5asGM3awyCCJdlobcTmaKWdFRI1MOb
            PZ8N7eR9hZqKQfOWq5BFU7j+UQhnGTa7/6Cmfd6PFZZwvbbtyenDeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T11:22:01Z"
    mac: ENC[AES256_GCM,data:/vquBFnDSInoVd5HXcsZhezNWrN+XKDijbIQ234Fj5tgxkocG0LG3bXED1StUhmlWjnglh4ipHr7SP6jUBmD2I1Rc1qtEH7vk0XyErwc7NTOfXS02hdkvN/lkDP8y0yfcmpVFr0su3o+hi7sNY5zVv9wvBuLy0zDm1wZSQ3fQtc=,iv:1MAoMT3oQg9ESJc1GkKEgcVLzBxQge2fZii++p0h2Ns=,tag:K9j091mKUnwl1I4N+vIgQg==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.11.0
