apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: nextcloud-schedule
spec:
  backend:
    s3:
      endpoint: s3.eu-central-003.backblazeb2.com
      bucket: bigli-io-talos-nextcloud-backup
      accessKeyIDSecretRef:
        name: backup-bucket-credentials
        key: access-key-id
      secretAccessKeySecretRef:
        name: backup-bucket-credentials
        key: access-key-secret
    repoPasswordSecretRef:
      name: backup-bucket-credentials
      key: password
  podSecurityContext:
    fsGroup: 33
    runAsUser: 33
  backup:
    schedule: '0 1 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    # optional
    #promURL: https://prometheus-io-instance:8443
  check:
    schedule: '0 3 * * 1'
    # optional
    #promURL: https://prometheus-io-instance:8443
  prune:
    schedule: '0 4 * * 0'
    retention:
      keepLast: 5
      keepDaily: 14
