apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres
  annotations:
    k8up.io/backupcommand: '/bin/bash -c "pg_dump -Fc -d nextcloud"'
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  instances: 1
  enablePDB: false

  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-postgres-user

  managed:
    roles:
      - name: nextcloud
        superuser: true
        login: true

  storage:
    size: 4Gi
    storageClass: hcloud-volumes
