apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
files:
  - backup-credentials-secret.sops.yaml
  - nextcloud-creds.sops.yaml
  - nextcloud-postgres-user.sops.yaml
  - nextcloud-valkey-user.sops.yaml
