apiVersion: v1
kind: Secret
metadata:
    name: backup-bucket-credentials
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:+Y9w6I+hw2nYfb0kqsES+RgEZ5Bd5Z2W+Q==,iv:ZDGHEKKYkLBTcik3Ot1aQATGURWHlsaZxB6oEnQ/OYk=,tag:JaJ0XvJ3gXXW9N2EXzaBRQ==,type:str]
    access-key-secret: ENC[AES256_GCM,data:wmP462IyoOel8ow30CuZPfuJzb2rV8PFFF4rKMtfdw==,iv:mYTajVnnMMQ5m9i8GiXIc0kztr+tg3QDZP2/EfsHXdE=,tag:fevvhvlpmrj+GTtjx5eHdw==,type:str]
    password: ENC[AES256_GCM,data:08jvYjhn+TyeMJ2C2jw3Rudz0FFF4nR4gKq0qI22xqo=,iv:8cyTvzaK9/S4AjTyVW5df6GW51B/OFHIlijSeQDD2o0=,tag:hX/3dx8xITPYc/V6/8zfPg==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRVY4NmNCZjdhMXI2Mkp5
            ZkIxVXM5SnMySFJiWlRoVmRXc1V5M3ZYZTBjCmhycTlBRXkxbk5idEIzeWp1UXND
            M0pJMjNHMnA2c1RJVEMyZGF3ekI1blkKLS0tIGIyMVJpb2JNckxnSFd2ZkNlMUJF
            MWQ3VzVYZGk2NzVsTU5BVnFDTFJQVlkKy5sw2AQLO+oXrGLHRoO4qpr25l+rNvlU
            ChPdwaNtbZqzE983W972cSM7ByMIM2+B5/M0hnZ9GThmM54w2632lQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc21ETEJGOHJwZU02TEZn
            TGxLTU82ZEdSVVp6WkZsMDFzSVZhVDk3SnpnCmQveFozQzU2UDEvU29seVRrSm5o
            RXZlampoYjJDZEdZZzQxTDJUQVBPMW8KLS0tIHVqUG1LV2hrdTU1N2NhM3RHWk5i
            cjVIU0FpdGUzRG5pL2dyOHM0Yms5OGMKjLfEWxTJDRo7E3gMNVmig5BHKzwnxnkE
            1B9/hJrUlST52+BvIfBrEKC2ol8pmGCZJhwSn0kT6/3H5YvnsW8p6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4T0hSaUova0lDQ0xka1pm
            U3pnVkFMejN0TGVONkRNRXIxSVVwZ0JwaXdZCmpST2MxQXVPS3RTVTVaUHRrMGxQ
            REhIdGhPaWduWVo0L01IbUtLV0hPa3MKLS0tIFRnMnhzYUs5N2dnMXhqSTJ5VTJu
            cGRVS0J6cDNOKzRzT2licFVMeE4vcFUKmFhJMDEdQ8aT+uY6QBR+v8VPsfyi1tYS
            cVlSb9fIum0a1NIDzfivN64YCqnPJdZoBSXTT3sDR5iNwuNlEZdL4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T21:10:33Z"
    mac: ENC[AES256_GCM,data:g2BIGftVA+/ETeevu47IL1TCpxWBFdvi0Bp0JNffpsXhAFZuC+aRtZYUuBs3DvQkuRKgoxZiluljS9KbSHl5vCoPGuuUuGJ3FKOB25wTeCV2aDBGikCn3OU/NbLPVbkYViMUkaAN4EnVOIVKnP4eXXTPgBWvrcv4E75MpeTzHSg=,iv:xaA9nUeEF+rASLwUvW2mCY7GFpBglBwNOkF1ZYcfw6k=,tag:efWc+jcwWhkse8bOSs09eA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
