apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headscale-route
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik-system
    sectionName: websecure
  hostnames:
  - "headscale.bigli.io"
  rules:
  - backendRefs:
    - name: headscale
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headscale-route-redirect
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik-system
    sectionName: web
  hostnames:
  - "headscale.bigli.io"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
