apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - envoyconfig.yaml
  - statefulset.yaml
  - service.yaml
  - httproute.yaml
generators:
  - secret-generator.yaml
