apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: headscale
stringData:
    noise_private.key: ENC[AES256_GCM,data:dHD1svgdh0Liap42b0rxFk/ywmwQP+gAQ0foSYd1PMbMitBftm5ROp0DL2lOwZQ0yQspflou/ObJ2kfYLgSCFElnqZxOkjkZ,iv:XEVQwivKh0qiac7DFGXESigf9+aCEMo8NI2gZjhijhU=,tag:JuErMqcg3gsdiqEouNmo4A==,type:str]
    private.key: ENC[AES256_GCM,data:xZdjwzXckLYaFHJWstnJ8X7zcDSnnuj8qazMJIwsxIKkrS9B6u4GBW8rpRfd7HpQRQSXgL6zMEhzPnz60wO/FBz3LnoduHpk,iv:g+dpJf+NX8HX4+OPldoFSzB+r3KCrjCJjgvIPMKiFdw=,tag:G7T+GmtAAK0R6I5YeK8KvQ==,type:str]
sops:
    age:
        - recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHpZWWFValhNeEVPaXZ2
            eCtNVEZveitQL3ViaWRicHZJckJ1N29jejJVClNUTkFVVXZiWlpxTFlac2ZTeE1J
            dWR2MEVmaENCTm9MNDJUYUJBUEgzL0kKLS0tIGVac2FHUXBEclBqcHpLd1hVd0d0
            bU1PUG5Na3M2aXBLZTRhVG16WnB3WlUKoiKlACgJBYpEpkmzN0wHQuPYpx7POvaa
            ur0/Y6nzyaRY4Q/YR18QuEoYFPFhcs7J88t2k2MV9Kc8HmbKJYCQvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd2czekFVODBhYkdzTlV0
            Yk1heGFBaS9tYXR4NTBrcGpQWFZhNHBjbG5zCnFTQUlOcWpvVzNoTmJtWE4ySU1o
            S0NjNHRaR0NQSGJtWEhieEpCa21mRTAKLS0tIEtranRyWXhVRm1kNVRGQTd0WUY5
            OE5YRldXcFduMVU1UnFrYytaN2V5LzgKCzdl3EtXIAJdRtSvJoYeaSIfdoZNCJRN
            KpoAimxlntvTOUVw5JXYgUpxEXwOu+/H47z6Tl1O3dhU3cFRh+v9BQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQL1kzaXdTZXM4QlVDNy8z
            Rk00SnhaZmxiRW9obE1yTDBsVWtmeUM1eWlRCmJMN3hYYzZBZ0FWNjgwcEc1ek8x
            RFRWbzBnL1B5cXVmbmU2UFNtRmRXdUEKLS0tIDI0Sy9DOS9qRTl2SWhxaXM4aDZy
            Vlo5Q1R3TnZSVzg2MzZrb2F0KzhheUUKcBxbbB8g0j75C+Cjqb7h6ut9Si9x0Dia
            jrzq9xRdCKLdFYG1XExt7+dorHSBrUf1rOIpt2u29CBRIeZUjILjyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T10:01:04Z"
    mac: ENC[AES256_GCM,data:xdSGWFD0YKXNGKVuFY1UH9rGeYaaRZZnPKQtAoWji6+Kgu7L/I6aZwI/7Zw8qCJosr2Wypnb+USXpWDXi86C+3bWtG6OP0tfzA/eLTQ2t1UmpgceZFO+DovrVQRjjw6rXAzCXwi1qgM0h6dfDTeEJ+PX0t6Bjax0bUAfRgC3r+A=,iv:vNAPR2reztV2MDLoBnaY1cGWm+Gs1PicqF9j/KB1inQ=,tag:KiD+KjtewJr3BTGKeQT0Xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
